apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
  labels:
    app: converter
data:
  # Application settings
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_CHANNEL: "stderr"
  
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"
  
  # MongoDB Configuration  
  MONGODB_HOST: "host.minikube.internal"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "mp3converter"
  MONGODB_VIDEOS_BUCKET: "videos"
  MONGODB_MP3S_BUCKET: "mp3s"
  
  # Queue names
  VIDEO_QUEUE: "video"
  MP3_QUEUE: "mp3"
