apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  APP_NAME: AuthService
  APP_ENV: production
  APP_DEBUG: "true"
  APP_URL: http://auth:5000
  LOG_CHANNEL: stderr
  LOG_LEVEL: info
  DB_CONNECTION: mysql
  DB_HOST: host.minikube.internal
  DB_PORT: "3306"
  DB_DATABASE: microservices
  DB_USERNAME: default
  JWT_TTL: "1440"
  JWT_ALGO: HS256
